### PR TITLE
Fix unused imports refactor so it doesn't lose inner types.

### LINKED ISSUE #15: UnusedImportRefactor can lose references to inner classes
Sometimes there are inner class references in imports. The UnusedImportRefactor can cause these to be lost.

Example:
import thispackage.MainClassDefn.InnerClass;

@ProvidedBy(InnerClass.class)
public class MainClassDefn {
   ...
   static InnerClass {...}
}

### PR DESCRIPTION
**Pull request by harrisric**
Fixes #15 
Also extends the test coverage for UnusedImportExample to cover some static variables.

### CODE REVIEW

**Comment by harrisric** [comment]
Actually only partially works - still need to fix the case where the inner type referenced is another class within the same package.

File: astra-core/src/main/java/org/alfasoftware/astra/core/refactoring/operations/imports/UnusedImportRefactor.java [hunk 1]
```diff
@@ -141,6 +142,11 @@ public void run(CompilationUnit compilationUnit, ASTNode node, ASTRewrite rewrit
     }
   }
 
+  /**
+   * Tracks any
```
Comment (RadikalJin) [inline astra-core/src/main/java/org/alfasoftware/astra/core/refactoring/operations/imports/UnusedImportRefactor.java:146]: Looks like this might have been missed - perhaps we just remove this block, and we make the code more self-documenting by renaming the inner type something like "JavadocTypesVisitor"?

File: astra-core/src/main/java/org/alfasoftware/astra/core/refactoring/operations/imports/UnusedImportRefactor.java [hunk 2]
```diff
@@ -48,30 +48,31 @@ public void run(CompilationUnit compilationUnit, ASTNode node, ASTRewrite rewrit
...
             AstraUtils.removeImport(compilationUnit, importDeclaration, rewriter);
             continue;
           }
-          
+
           // remove imports for types in the same package
           if (compilationUnit.getPackage().getName().toString().equals(
-            AstraUtils.getPackageName(importDeclaration.getName().toString()))) {
+            AstraUtils.getPackageName(importDeclaration.getName().toString()))
+            && !AstraUtils.isImportOfInnerType(importDeclaration)) {
```
Comment (RadikalJin) [inline astra-core/src/main/java/org/alfasoftware/astra/core/refactoring/operations/imports/UnusedImportRefactor.java:71]: Nice! This is a straightforward approach.

**Comment by RadikalJin** [comment]
Hi @harrisric, thank you for your contribution - it looks like it'll be a nice improvement for the UnusedImportRefactor!

It looks like the build is a bit unhappy at the moment - thanks for bearing with me while that gets sorted out...
